language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
  - mvn clean package --settings settings.xml

deploy:
  provider: script
  script: mvn clean deploy --settings settings.xml
  on:
    branch: test